name: Playwright demo dotnet tests
on:
  push:
  workflow_dispatch:
  schedule:
    # run at minute 5 past every 3rd hour from 2 through 23
    - cron: '5 2/3 * * *'
jobs:
  playwright-demo-dotnet:
    name: Playwright version 1.25
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./playwright-demo-dotnet
    # stop the job if it runs over 115 minutes
    # to prevent a hanging process from using CI minutes
    timeout-minutes: 115
    steps:
      - name: Delete workflow runs older than one week
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 7
          keep_minimum_runs: 10
      - name: Checkout
        uses: actions/checkout@v3
      # Version 3.1.x is required for trx-to-html report generator only
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: | 
            3.1.x
            6.0.x
      - name: Install dependency Microsoft.Playwright
        run: dotnet add package Microsoft.Playwright --version 1.25.0
      - name: Install dependency Microsoft.Playwright.NUnit
        run: dotnet add package Microsoft.Playwright.NUnit --version 1.25.0
      - name: Build
        run: dotnet build
      - name: Playwright install
        run: pwsh ./bin/Debug/net6.0/playwright.ps1 install --with-deps
      - name: Run tests
        run: dotnet test -e BROWSER=chromium --logger trx --results-directory "TestResults-6.0.x"
      - name: Install trx-to-html report generator
        run: cd TestResults-6.0.x | dotnet tool install -g Samhammer.TrxToHtml
      - name: Run trx-to-html to generate html report
        run: cd TestResults-6.0.x | trx-to-html
      - name: Move and rename trx-to-html generated html report
        run: mv ./TestResults.html ./TestResults-6.0.x/index.html
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: dotnet-results-6.0.x
          path: playwright-demo-dotnet/TestResults-6.0.x
          if-no-files-found: ignore
      - name: Deploy Cypress report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: playwright-demo-dotnet/TestResults-6.0.x
          destination_dir: docs
